name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main  # Se ejecuta cuando haces push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar PHP y Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Ajusta según tu versión
        tools: composer

    - name: Instalar dependencias Laravel
      run: |
        composer install --no-dev --prefer-dist
        chmod -R 777 storage bootstrap/cache

    - name: Crear artefacto ZIP
      run: zip -r laravel_app.zip . -x "*.git*" "vendor/*"

    - name: Subir artefacto ZIP como build
      uses: actions/upload-artifact@v4
      with:
        name: laravel_artifact
        path: laravel_app.zip

  transfer:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Descargar artefacto
      uses: actions/download-artifact@v4
      with:
        name: laravel_artifact

    - name: Subir ZIP a EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        source: "laravel_app.zip"
        target: "/var/www/granada_prueba"

    - name: Desplegar en EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/granada_prueba
          unzip -o laravel_app.zip
          rm laravel_app.zip
          composer install --no-dev --prefer-dist
          php artisan migrate --force
          php artisan config:clear
          php artisan cache:clear
          php artisan queue:restart
          sudo systemctl restart nginx
